### ISSUE TITLE
Question about training device

### ISSUE THREAD

**Issue by plusgrey** [Ivan-Tang-3D/Any2Point#1]
Hi,

Thanks for your excellent work. May I know the number of GPUs and the specific device name of your training process?

**Comment by Ivan-Tang-3D** [comment]
> Hi,
> 
> Thanks for your excellent work. May I know the number of GPUs and the specific device name of your training process?

We train the whole models on one A100 80G GPU. However, the training of CLIP Text Encoder could run on GPU with memory>28G. The remaining codes and models I will release these days.
