### ISSUE TITLE
Question about vision model's checkpoint 

### ISSUE THREAD

**Issue by Dali936** [Ivan-Tang-3D/Any2Point#3]
Hi, dear author, thanks for your amazing work ! i am confirming whether the vision model's checkpoint is '[dinov2_vitb14_pretrain.pth]'
<img width="726" alt="图片1" src="https://github.com/user-attachments/assets/5d10d71e-3c6e-4a64-96e1-88adff8a3d5c">

**Comment by Ivan-Tang-3D** [comment]
> Hi, dear author, thanks for your amazing work ! i am confirming whether the vision model's checkpoint is '[dinov2_vitb14_pretrain.pth]' <img alt="图片1" width="726" src="https://private-user-images.githubusercontent.com/83868746/360405126-5d10d71e-3c6e-4a64-96e1-88adff8a3d5c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMjU4OTksIm5iZiI6MTcyNDMyNTU5OSwicGF0aCI6Ii84Mzg2ODc0Ni8zNjA0MDUxMjYtNWQxMGQ3MWUtM2M2ZS00YTY0LTk2ZTEtODhhZGZmOGEzZDVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDExMTk1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhMTg4YTg1OGI4YTFiYjY0MGMyMmM1MmNlN2NlMWRlMDY4ODIxYWY5OWVjMGQxMzkwYjk0N2ZjNWYyZmM4YjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s33CX4JOK4WInntcZyC_g5OEOnTGXb8PlVRCJYXNsPQ">

Yeah，I think so.

**Comment by Dali936** [comment]
> > Hi, dear author, thanks for your amazing work ! i am confirming whether the vision model's checkpoint is '[dinov2_vitb14_pretrain.pth]' <img alt="图片1" width="726" src="https://private-user-images.githubusercontent.com/83868746/360405126-5d10d71e-3c6e-4a64-96e1-88adff8a3d5c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMjU4OTksIm5iZiI6MTcyNDMyNTU5OSwicGF0aCI6Ii84Mzg2ODc0Ni8zNjA0MDUxMjYtNWQxMGQ3MWUtM2M2ZS00YTY0LTk2ZTEtODhhZGZmOGEzZDVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDExMTk1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhMTg4YTg1OGI4YTFiYjY0MGMyMmM1MmNlN2NlMWRlMDY4ODIxYWY5OWVjMGQxMzkwYjk0N2ZjNWYyZmM4YjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s33CX4JOK4WInntcZyC_g5OEOnTGXb8PlVRCJYXNsPQ">
> 
> Yeah，I think so.

thanks for your clearly reply
